const BLACKLISTED_EMAILS = [
    "ivan.fisher@ibuv.org",
    "john@budeher.co.uk",
    "violet@kuwa.org",
    "matilda.walton@abu.io",
  ];
  
  const database = {
    data: [
      {
        name: "Sallie",
        email: "dean@tinug.com",
        password: "RZRl",
        isAdmin: false,
      },
      {
        name: "Clifford",
        email: "mayme.berry@gegizev.co.uk",
        password: "ifKG2KSE",
        isAdmin: false,
      },
      {
        name: "Kyle",
        email: "oscar.moreno@tulid.co.uk",
        password: "oD9k8fO1S",
        isAdmin: false,
      },
      {
        name: "Abbie",
        email: "willie@fogipa.io",
        password: "Tyqw",
        isAdmin: false,
      },
      {
        name: "Adeline",
        email: "derrick@dujuli.io",
        password: "gZW6cZ8K",
        isAdmin: false,
      },
      {
        name: "Patrick",
        email: "fannie.banks@gasola.com",
        password: "TORlA8Zg",
        isAdmin: false,
      },
      {
        name: "Celia",
        email: "sally.haynes@locefa.net",
        password: "KAFdt0",
        isAdmin: false,
      },
      {
        name: "Bessie",
        email: "cecelia@umemuwi.edu",
        password: "5CXOBcRXm",
        isAdmin: false,
      },
      {
        name: "Keith",
        email: "rhoda.barrett@nes.edu",
        password: "CD7T",
        isAdmin: false,
      },
      {
        name: "Gordon",
        email: "jessie@zadiji.com",
        password: "x5w7",
        isAdmin: false,
      },
      {
        name: "Isabelle",
        email: "rosa@derepa.gov",
        password: "rDdtwHVM08",
        isAdmin: false,
      },
      {
        name: "Eleanor",
        email: "micheal@jicel.edu",
        password: "Nhfoj7J2R",
        isAdmin: false,
      },
      {
        name: "Walter",
        email: "micheal@sizoh.co.uk",
        password: "hKDn",
        isAdmin: false,
      },
      {
        name: "Winnie",
        email: "leo.cannon@ubi.com",
        password: "rOqW",
        isAdmin: false,
      },
      {
        name: "Ina",
        email: "sophie@gujap.io",
        password: "U4XhE49L",
        isAdmin: false,
      },
      {
        name: "Roy",
        email: "jared@moc.co.uk",
        password: "APPdKs6U",
        isAdmin: false,
      },
      {
        name: "Louis",
        email: "erik@zag.io",
        password: "7TgxBfok9",
        isAdmin: false,
      },
      {
        name: "Alma",
        email: "duane.stephens@ramo.net",
        password: "f93j",
        isAdmin: false,
      },
      {
        name: "Russell",
        email: "michael@opigaz.org",
        password: "IrCV",
        isAdmin: false,
      },
      {
        name: "Nicholas",
        email: "lilly.dixon@okojob.edu",
        password: "hGSYPuEP6",
        isAdmin: false,
      },
      {
        name: "Genevieve",
        email: "lewis@amu.com",
        password: "bBgqLg",
        isAdmin: false,
      },
      {
        name: "Ricky",
        email: "cole.lowe@wakino.gov",
        password: "1a6uIh",
        isAdmin: false,
      },
      {
        name: "Donald",
        email: "rosetta@minig.io",
        password: "uKJs",
        isAdmin: false,
      },
      {
        name: "Margaret",
        email: "jennie@etel.net",
        password: "WeFKbVfdo",
        isAdmin: false,
      },
      {
        name: "Edna",
        email: "ruth@repa.gov",
        password: "QIJ0",
        isAdmin: false,
      },
      {
        name: "Calvin",
        email: "isabel.roy@cotu.edu",
        password: "WCLhUfEaXS",
        isAdmin: false,
      },
      {
        name: "Mae",
        email: "mabelle.tucker@cabisav.org",
        password: "OCUhxBt6W",
        isAdmin: false,
      },
      {
        name: "Mittie",
        email: "mathilda@uriled.io",
        password: "AdCxTB",
        isAdmin: false,
      },
      {
        name: "Violet",
        email: "rebecca.olson@izujemu.co.uk",
        password: "USDtxEU0",
        isAdmin: false,
      },
      {
        name: "Cody",
        email: "oscar.schmidt@anirim.com",
        password: "LfzBF",
        isAdmin: false,
      },
      {
        name: "Aaron",
        email: "james@rit.co.uk",
        password: "kpzKtHokF",
        isAdmin: false,
      },
      {
        name: "Tom",
        email: "virgie@ates.com",
        password: "BvBcICi",
        isAdmin: false,
      },
      {
        name: "Edward",
        email: "rena@zat.org",
        password: "2OQYuggsoe",
        isAdmin: false,
      },
      {
        name: "Olga",
        email: "seth@lege.edu",
        password: "bnStHa",
        isAdmin: false,
      },
      {
        name: "Gene",
        email: "oscar.hoffman@oga.gov",
        password: "oeCYfXY",
        isAdmin: false,
      },
      {
        name: "Augusta",
        email: "manuel@dicivib.org",
        password: "t3jF6Vc",
        isAdmin: false,
      },
      {
        name: "Gertrude",
        email: "birdie@etaniv.gov",
        password: "L7IULdoDw",
        isAdmin: false,
      },
      {
        name: "Aaron",
        email: "sam@inikeki.org",
        password: "YMCiZ",
        isAdmin: false,
      },
      {
        name: "Helen",
        email: "katie@luvuwuc.net",
        password: "noyDrwHv0p",
        isAdmin: false,
      },
      {
        name: "Ruby",
        email: "clara@wezuli.edu",
        password: "YpSAvO1m",
        isAdmin: false,
      },
      {
        name: "Daniel",
        email: "vernon.garcia@job.com",
        password: "Edksz",
        isAdmin: false,
      },
      {
        name: "Ina",
        email: "marguerite@kafer.gov",
        password: "YgfFrHHG",
        isAdmin: false,
      },
      {
        name: "Edwin",
        email: "lloyd.rodriquez@kep.io",
        password: "5J4HRp",
        isAdmin: false,
      },
      {
        name: "Jerome",
        email: "bernard@nod.io",
        password: "SO99l",
        isAdmin: false,
      },
      {
        name: "Shawn",
        email: "elnora@poki.gov",
        password: "G7nDeogZ",
        isAdmin: false,
      },
      {
        name: "Ann",
        email: "zachary@urik.org",
        password: "6Dx5G3s",
        isAdmin: false,
      },
      {
        name: "Melvin",
        email: "estella.bass@rodehur.edu",
        password: "58FVR",
        isAdmin: false,
      },
      {
        name: "Troy",
        email: "alberta.luna@arasi.com",
        password: "B8rObQ",
        isAdmin: false,
      },
      {
        name: "Minnie",
        email: "jeffrey.briggs@omifu.com",
        password: "F9wEy",
        isAdmin: false,
      },
      {
        name: "Fanny",
        email: "alice@govamap.co.uk",
        password: "F2Utncy",
        isAdmin: false,
      },
      {
        name: "Matthew",
        email: "tommy.welch@guh.io",
        password: "gAKiW3J5S",
        isAdmin: false,
      },
      {
        name: "Sadie",
        email: "lina@dehah.net",
        password: "Xqzb1",
        isAdmin: false,
      },
      {
        name: "Nathaniel",
        email: "marvin@finen.io",
        password: "Ubqz",
        isAdmin: false,
      },
      {
        name: "Jordan",
        email: "leona@fosifo.gov",
        password: "x4Vlwt3",
        isAdmin: false,
      },
      {
        name: "Andre",
        email: "nellie.griffin@sujuf.co.uk",
        password: "qO3Z7hBJ",
        isAdmin: false,
      },
      {
        name: "Randall",
        email: "johanna@upegoba.io",
        password: "ilc1cSGoDz",
        isAdmin: false,
      },
      {
        name: "Julia",
        email: "alejandro@cud.gov",
        password: "8MA19z",
        isAdmin: false,
      },
      {
        name: "Effie",
        email: "mario@tosofu.io",
        password: "c81WMbmuV2",
        isAdmin: false,
      },
      {
        name: "Frederick",
        email: "leroy.west@cud.gov",
        password: "pqB5mciW3",
        isAdmin: false,
      },
      {
        name: "Cody",
        email: "phillip@jebezo.gov",
        password: "L3dY2QT",
        isAdmin: false,
      },
      {
        name: "Dorothy",
        email: "rebecca.phillips@edu.edu",
        password: "4s0wI",
        isAdmin: false,
      },
      {
        name: "Kate",
        email: "mathilda@ohajo.co.uk",
        password: "IdEyqHvGc",
        isAdmin: false,
      },
      {
        name: "Sallie",
        email: "curtis@ugito.org",
        password: "IpiTS4zRzV",
        isAdmin: false,
      },
      {
        name: "Gavin",
        email: "jay@ekob.org",
        password: "2a1Zjbw4E",
        isAdmin: false,
      },
      {
        name: "Katie",
        email: "curtis@hokisa.com",
        password: "Hk9k6fw",
        isAdmin: false,
      },
      {
        name: "Marguerite",
        email: "nelle@pame.edu",
        password: "JjIY3J36S",
        isAdmin: false,
      },
      {
        name: "Alejandro",
        email: "gilbert.ball@jab.gov",
        password: "Pi6mlDC",
        isAdmin: false,
      },
      {
        name: "Garrett",
        email: "eva@bal.com",
        password: "tUQMk32g",
        isAdmin: false,
      },
      {
        name: "Carlos",
        email: "brett.taylor@fisihu.co.uk",
        password: "08QS",
        isAdmin: false,
      },
      {
        name: "Scott",
        email: "kenneth@hidapo.net",
        password: "7I88FaPz",
        isAdmin: false,
      },
      {
        name: "Minerva",
        email: "jonathan.barber@vifudu.io",
        password: "XSiHjTQ",
        isAdmin: false,
      },
      {
        name: "Clarence",
        email: "gilbert.hicks@met.net",
        password: "8fIQ321",
        isAdmin: false,
      },
      {
        name: "Ricky",
        email: "willie@rih.net",
        password: "RgzrmIAEy",
        isAdmin: false,
      },
      {
        name: "Willie",
        email: "charlotte.williams@ali.co.uk",
        password: "Tk6J0f",
        isAdmin: false,
      },
      {
        name: "Luella",
        email: "willie@fur.edu",
        password: "Tnomw",
        isAdmin: false,
      },
      {
        name: "Jayden",
        email: "charles@taz.edu",
        password: "DLJGo5KEM",
        isAdmin: false,
      },
      {
        name: "Marian",
        email: "linnie@mokom.com",
        password: "JDhh8Z",
        isAdmin: false,
      },
      {
        name: "Tommy",
        email: "gavin.swanson@jewajuv.co.uk",
        password: "cpYZAj",
        isAdmin: false,
      },
      {
        name: "Fred",
        email: "nellie.hicks@eracup.com",
        password: "LTeHLdjHjW",
        isAdmin: false,
      },
      {
        name: "Jackson",
        email: "bessie@poka.io",
        password: "XajZ",
        isAdmin: false,
      },
      {
        name: "Alex",
        email: "eleanor@osel.org",
        password: "tnJEDb",
        isAdmin: false,
      },
      {
        name: "Tom",
        email: "clara.moss@gonako.gov",
        password: "nwBi",
        isAdmin: false,
      },
      {
        name: "Luke",
        email: "mason@dap.io",
        password: "7tCSgV5dQ",
        isAdmin: false,
      },
      {
        name: "Marie",
        email: "dean.davis@nevosi.io",
        password: "akJ3Uk",
        isAdmin: false,
      },
      {
        name: "Sophie",
        email: "harold.tyler@mudo.net",
        password: "zbkipP7Y9b",
        isAdmin: false,
      },
      {
        name: "Nina",
        email: "mattie@abot.gov",
        password: "0q85",
        isAdmin: false,
      },
      {
        name: "Eliza",
        email: "brent.little@nohek.edu",
        password: "N89Fd3Nr8Y",
        isAdmin: false,
      },
      {
        name: "Mae",
        email: "fannie.atkins@zuse.edu",
        password: "96YM3vwbm",
        isAdmin: false,
      },
      {
        name: "Carl",
        email: "walter.morrison@munocu.net",
        password: "7jevXC4Y",
        isAdmin: false,
      },
      {
        name: "Rosie",
        email: "ruth.shaw@pimedid.edu",
        password: "8ZtA",
        isAdmin: false,
      },
      {
        name: "Lura",
        email: "marvin.sparks@wegok.com",
        password: "P9GjvtAa",
        isAdmin: false,
      },
      {
        name: "Margaret",
        email: "francis.waters@vilame.co.uk",
        password: "9qFbb3WrJ",
        isAdmin: false,
      },
      {
        name: "Carl",
        email: "lawrence@ecakum.io",
        password: "FqZyFsYze",
        isAdmin: false,
      },
      {
        name: "Harold",
        email: "maude@rido.org",
        password: "ulGe6Pgs",
        isAdmin: false,
      },
      {
        name: "Susan",
        email: "chester.warner@kigol.gov",
        password: "OAtb",
        isAdmin: false,
      },
      {
        name: "Sallie",
        email: "owen@heji.net",
        password: "JIlpq5KeY",
        isAdmin: false,
      },
      {
        name: "Emilie",
        email: "dominic.powers@miziti.net",
        password: "t8CDJpy",
        isAdmin: false,
      },
      {
        name: "Marie",
        email: "katie.haynes@buf.io",
        password: "6yRWIK",
        isAdmin: false,
      },
      {
        name: "Matthew",
        email: "ethel@pifafi.com",
        password: "lLiY0mlYQ",
        isAdmin: false,
      },
      {
        name: "Stella",
        email: "katie@dam.co.uk",
        password: "2OwBqdi",
        isAdmin: false,
      },
      {
        name: "Ada",
        email: "jacob@havip.org",
        password: "48b7ObS1",
        isAdmin: false,
      },
      {
        name: "Ina",
        email: "joseph@ducu.edu",
        password: "C2or6Ys",
        isAdmin: false,
      },
      {
        name: "Jonathan",
        email: "annie@toh.edu",
        password: "8ZtWt",
        isAdmin: false,
      },
      {
        name: "Chris",
        email: "mamie.romero@ajeha.io",
        password: "7HlZMRI",
        isAdmin: false,
      },
      {
        name: "Edith",
        email: "kyle@olamiz.com",
        password: "VBHpKwUR",
        isAdmin: false,
      },
      {
        name: "Cody",
        email: "grace.king@ofeda.gov",
        password: "OirJi",
        isAdmin: false,
      },
      {
        name: "David",
        email: "tyler.neal@cep.io",
        password: "nRgET4qI",
        isAdmin: false,
      },
      {
        name: "Noah",
        email: "sallie.dawson@jofum.net",
        password: "auyM",
        isAdmin: false,
      },
      {
        name: "Henrietta",
        email: "frederick@jowasot.io",
        password: "YE8Mm",
        isAdmin: false,
      },
      {
        name: "Steven",
        email: "alvin.norman@warud.com",
        password: "XmOzxcM9",
        isAdmin: false,
      },
      {
        name: "Augusta",
        email: "lilly@vupo.net",
        password: "Wgrgn",
        isAdmin: false,
      },
      {
        name: "Devin",
        email: "alan.owen@kagawe.com",
        password: "udy1K",
        isAdmin: false,
      },
      {
        name: "Alex",
        email: "henry.christensen@fisaka.net",
        password: "Uk4YL7",
        isAdmin: false,
      },
      {
        name: "Katie",
        email: "luella.cain@jeno.com",
        password: "M4cy",
        isAdmin: false,
      },
      {
        name: "Ralph",
        email: "tom.harrison@lipic.co.uk",
        password: "VnoySnfm7",
        isAdmin: false,
      },
      {
        name: "Jesse",
        email: "keith@letog.net",
        password: "xat5ci",
        isAdmin: false,
      },
      {
        name: "Bradley",
        email: "corey@focim.io",
        password: "hthS",
        isAdmin: false,
      },
      {
        name: "Timothy",
        email: "hulda@sugogi.net",
        password: "hldJsoS0",
        isAdmin: false,
      },
      {
        name: "Randall",
        email: "cole.maxwell@inop.net",
        password: "iAMDryivI4",
        isAdmin: false,
      },
      {
        name: "Myrtle",
        email: "maud@bacapap.com",
        password: "xv1uo",
        isAdmin: false,
      },
      {
        name: "Jared",
        email: "edward.armstrong@hevud.com",
        password: "dvFdJ",
        isAdmin: false,
      },
      {
        name: "Kate",
        email: "earl.carpenter@kivil.net",
        password: "IL6SRqbfWx",
        isAdmin: false,
      },
      {
        name: "Norman",
        email: "charlotte.hayes@zesamun.co.uk",
        password: "Oggrt0ArMU",
        isAdmin: false,
      },
      {
        name: "Bryan",
        email: "angel.ray@ohok.io",
        password: "i3wTG",
        isAdmin: false,
      },
      {
        name: "Bagas",
        email: "bagas_ganteng@priambudi.fyi",
        password: "password",
        isAdmin: true,
      },
      {
        name: "Carlos",
        email: "leroy.rose@urage.co.uk",
        password: "RgbOU6",
        isAdmin: false,
      },
      {
        name: "Pearl",
        email: "evelyn@ehec.edu",
        password: "gsufTB",
        isAdmin: false,
      },
      {
        name: "Elnora",
        email: "lucas.warren@migalo.com",
        password: "RH11",
        isAdmin: false,
      },
      {
        name: "Callie",
        email: "johanna.payne@zasoko.com",
        password: "SXrUI",
        isAdmin: false,
      },
      {
        name: "Manuel",
        email: "austin@usi.co.uk",
        password: "kxrfK6",
        isAdmin: false,
      },
      {
        name: "Logan",
        email: "corey@imowa.org",
        password: "Ub0KXzca4v",
        isAdmin: false,
      },
      {
        name: "Dennis",
        email: "russell.patrick@komus.gov",
        password: "XWxmYkvpnn",
        isAdmin: false,
      },
      {
        name: "Laura",
        email: "angel.roberson@jegero.com",
        password: "skqzjb5s",
        isAdmin: false,
      },
      {
        name: "Victoria",
        email: "lina.phelps@manido.org",
        password: "S6EEWX",
        isAdmin: false,
      },
      {
        name: "Maurice",
        email: "noah.perez@ewato.co.uk",
        password: "v6DyvVO",
        isAdmin: false,
      },
      {
        name: "Edna",
        email: "jonathan@tozo.edu",
        password: "KuCnumUbgD",
        isAdmin: false,
      },
      {
        name: "Edgar",
        email: "lora.patton@pemaw.net",
        password: "cIgBJWLE9y",
        isAdmin: false,
      },
      {
        name: "Ray",
        email: "gavin@pefow.com",
        password: "xEoOhnu",
        isAdmin: false,
      },
      {
        name: "Devin",
        email: "lucile@aligo.net",
        password: "avV1",
        isAdmin: false,
      },
      {
        name: "Millie",
        email: "martin@romud.org",
        password: "rnOe",
        isAdmin: false,
      },
      {
        name: "Ola",
        email: "emma@jol.io",
        password: "UR5bniS",
        isAdmin: false,
      },
      {
        name: "Brent",
        email: "ray.duncan@awi.net",
        password: "UDroR",
        isAdmin: false,
      },
      {
        name: "Margaret",
        email: "troy@cihof.io",
        password: "TL6pHVBGg",
        isAdmin: false,
      },
      {
        name: "Isabelle",
        email: "lura@nuva.gov",
        password: "KemF4pn",
        isAdmin: false,
      },
      {
        name: "Randy",
        email: "lola.schneider@hek.gov",
        password: "yuD5QzF",
        isAdmin: false,
      },
      {
        name: "Millie",
        email: "pearl.hardy@sumoto.net",
        password: "tz4fqA",
        isAdmin: false,
      },
      {
        name: "Calvin",
        email: "steven.norris@sugufup.net",
        password: "3axHje",
        isAdmin: false,
      },
      {
        name: "Jean",
        email: "lilly@ijinu.edu",
        password: "FeOZ",
        isAdmin: false,
      },
      {
        name: "Iva",
        email: "josephine.todd@lukudo.gov",
        password: "qYWmD",
        isAdmin: false,
      },
      {
        name: "Esther",
        email: "stephen.mclaughlin@bubawe.com",
        password: "y0saq4jO",
        isAdmin: false,
      },
      {
        name: "Mary",
        email: "jeanette@kaciwet.edu",
        password: "BG3u",
        isAdmin: false,
      },
      {
        name: "Barbara",
        email: "leroy@bowi.com",
        password: "fnDA",
        isAdmin: false,
      },
      {
        name: "Jordan",
        email: "inez.mendez@tiro.co.uk",
        password: "3fGEoBdf",
        isAdmin: false,
      },
      {
        name: "Nell",
        email: "nora@mafahim.org",
        password: "QGg4",
        isAdmin: false,
      },
      {
        name: "Allen",
        email: "vincent@alasiz.gov",
        password: "XsEl",
        isAdmin: false,
      },
      {
        name: "Ray",
        email: "marcus@gabimub.com",
        password: "QsWlBYix",
        isAdmin: false,
      },
      {
        name: "Josephine",
        email: "trevor@diwupe.co.uk",
        password: "rPIIlO4z",
        isAdmin: false,
      },
      {
        name: "Fanny",
        email: "charlie@kiravif.co.uk",
        password: "eWim7Ao2",
        isAdmin: false,
      },
      {
        name: "Ronnie",
        email: "clifford.wilkins@dobe.gov",
        password: "g035",
        isAdmin: false,
      },
      {
        name: "Nellie",
        email: "viola@ahico.org",
        password: "liQMwWaxP2",
        isAdmin: false,
      },
      {
        name: "Tony",
        email: "devin.chandler@ira.net",
        password: "auiZ14XSs",
        isAdmin: false,
      },
      {
        name: "Joshua",
        email: "bessie.carpenter@gunil.com",
        password: "n51xOx",
        isAdmin: false,
      },
      {
        name: "Barbara",
        email: "ida.perry@dusule.net",
        password: "L5wu",
        isAdmin: false,
      },
      {
        name: "Adrian",
        email: "kate@atusuri.io",
        password: "7zXfSn7L1R",
        isAdmin: false,
      },
      {
        name: "Lola",
        email: "lucas.ray@hozehu.net",
        password: "8Tj4",
        isAdmin: false,
      },
      {
        name: "Mina",
        email: "sophie@vizeh.com",
        password: "WS3E3IQ",
        isAdmin: false,
      },
      {
        name: "Delia",
        email: "bill.arnold@haf.com",
        password: "ibc1",
        isAdmin: false,
      },
      {
        name: "Lelia",
        email: "rebecca.peters@ejig.gov",
        password: "8WguXY",
        isAdmin: false,
      },
      {
        name: "Christina",
        email: "luella.mendez@julem.io",
        password: "o32d",
        isAdmin: false,
      },
      {
        name: "Alma",
        email: "shane.logan@wura.io",
        password: "FknKjah",
        isAdmin: false,
      },
      {
        name: "Lucille",
        email: "warren@fus.co.uk",
        password: "PqNODnWeWV",
        isAdmin: false,
      },
      {
        name: "Phoebe",
        email: "irene@picih.net",
        password: "QHJbBV",
        isAdmin: false,
      },
      {
        name: "Charlotte",
        email: "eva@keka.co.uk",
        password: "p00EfQ46e",
        isAdmin: false,
      },
      {
        name: "Eunice",
        email: "allie.robinson@pomuw.net",
        password: "dM3JEbDAYv",
        isAdmin: false,
      },
      {
        name: "Clarence",
        email: "isaac.webb@inadofo.io",
        password: "inwsy",
        isAdmin: false,
      },
      {
        name: "Ronald",
        email: "gilbert.black@zel.edu",
        password: "Y1zmURVB",
        isAdmin: false,
      },
      {
        name: "Billy",
        email: "dustin@bubom.net",
        password: "HvvjxHGd",
        isAdmin: false,
      },
      {
        name: "Philip",
        email: "georgia.holt@vilu.com",
        password: "ydPH41nX",
        isAdmin: false,
      },
      {
        name: "Louisa",
        email: "etta.sherman@hohev.co.uk",
        password: "Y6DLwaQA",
        isAdmin: false,
      },
      {
        name: "Kate",
        email: "sean@pusup.org",
        password: "32oPBoTmHr",
        isAdmin: false,
      },
      {
        name: "Harriett",
        email: "daniel.lyons@fot.net",
        password: "GU22j",
        isAdmin: false,
      },
      {
        name: "Allen",
        email: "charlotte.armstrong@rulazut.net",
        password: "OfEm4qD",
        isAdmin: false,
      },
      {
        name: "Sadie",
        email: "matilda.walton@abu.io",
        password: "6rvq",
        isAdmin: false,
      },
      {
        name: "Dylan",
        email: "zachary@kev.org",
        password: "UfEIcIlkL",
        isAdmin: false,
      },
      {
        name: "Travis",
        email: "manuel@dawicu.org",
        password: "EKOgd5OCk",
        isAdmin: false,
      },
      {
        name: "Linnie",
        email: "alan.mccoy@zin.net",
        password: "xz7xgtZJ7k",
        isAdmin: false,
      },
      {
        name: "Louise",
        email: "stephen.simmons@nure.edu",
        password: "NoZ0",
        isAdmin: false,
      },
      {
        name: "Aaron",
        email: "carolyn@ekozuh.gov",
        password: "R1YBo",
        isAdmin: false,
      },
      {
        name: "Ryan",
        email: "katharine@hofufa.gov",
        password: "8eiWW",
        isAdmin: false,
      },
      {
        name: "Ida",
        email: "wayne.mcdaniel@ipi.com",
        password: "MVXlHh",
        isAdmin: false,
      },
      {
        name: "Kevin",
        email: "joshua.torres@juken.net",
        password: "foSM",
        isAdmin: false,
      },
      {
        name: "Georgia",
        email: "esther@cut.gov",
        password: "c8FAxdf5n1",
        isAdmin: false,
      },
      {
        name: "Antonio",
        email: "lydia@jon.org",
        password: "MTDh9nAxs5",
        isAdmin: false,
      },
      {
        name: "Jonathan",
        email: "lena@nes.co.uk",
        password: "GsxCg9tN",
        isAdmin: false,
      },
      {
        name: "Sarah",
        email: "evelyn@hub.io",
        password: "6F3v4U0hfv",
        isAdmin: false,
      },
      {
        name: "Ola",
        email: "birdie@sob.co.uk",
        password: "MPxPed",
        isAdmin: false,
      },
      {
        name: "Bill",
        email: "bertie.abbott@rihucuz.io",
        password: "zhfZVcA6R",
        isAdmin: false,
      },
      {
        name: "Clifford",
        email: "sally@ane.edu",
        password: "lWuOYJ",
        isAdmin: false,
      },
      {
        name: "Louisa",
        email: "eunice.atkins@noret.net",
        password: "BMlcWlQ",
        isAdmin: false,
      },
      {
        name: "Hattie",
        email: "lucinda@moja.gov",
        password: "4TOspXKfmQ",
        isAdmin: false,
      },
      {
        name: "Alberta",
        email: "jared.neal@wejaf.com",
        password: "sLiiuF",
        isAdmin: false,
      },
      {
        name: "Martha",
        email: "abbie.wong@pola.edu",
        password: "Z1XPYcp3C",
        isAdmin: false,
      },
      {
        name: "Rose",
        email: "cole@rezu.com",
        password: "AzU0zNB",
        isAdmin: false,
      },
      {
        name: "Augusta",
        email: "jeremiah.lindsey@awecop.edu",
        password: "3cNqfBA0BS",
        isAdmin: false,
      },
      {
        name: "Lois",
        email: "shane@pebimi.edu",
        password: "EgfJF",
        isAdmin: false,
      },
      {
        name: "Jesse",
        email: "harriet.pierce@omu.net",
        password: "IC8R1kG6",
        isAdmin: false,
      },
      {
        name: "Lucy",
        email: "gene.mcgee@mip.co.uk",
        password: "d0qX",
        isAdmin: false,
      },
      {
        name: "Christopher",
        email: "isaiah.briggs@obujobe.edu",
        password: "8wA11u",
        isAdmin: false,
      },
      {
        name: "Jimmy",
        email: "lizzie@osap.io",
        password: "w3kQ5st",
        isAdmin: false,
      },
      {
        name: "Larry",
        email: "leonard@rowap.co.uk",
        password: "sWHEa29pX",
        isAdmin: false,
      },
      {
        name: "George",
        email: "lawrence@veruw.edu",
        password: "8Ud8YjyA",
        isAdmin: false,
      },
      {
        name: "Scott",
        email: "viola@cico.net",
        password: "gzuEWo",
        isAdmin: false,
      },
      {
        name: "John",
        email: "john.herrera@enogata.edu",
        password: "6RVO6wf5Vg",
        isAdmin: false,
      },
      {
        name: "Rosie",
        email: "annie.cooper@rufus.org",
        password: "P3doQflw3",
        isAdmin: false,
      },
      {
        name: "Mathilda",
        email: "genevieve@ujolus.net",
        password: "P2NVH",
        isAdmin: false,
      },
      {
        name: "Vincent",
        email: "trevor@mago.org",
        password: "IGHHPP",
        isAdmin: false,
      },
      {
        name: "Estella",
        email: "millie@teditoj.gov",
        password: "zckQ4",
        isAdmin: false,
      },
      {
        name: "Olga",
        email: "jorge@jukuzob.com",
        password: "SWPz",
        isAdmin: false,
      },
      {
        name: "Daniel",
        email: "eunice@lusij.org",
        password: "zP2lSU",
        isAdmin: false,
      },
      {
        name: "Hallie",
        email: "russell.richards@ogilal.io",
        password: "N7iuJk",
        isAdmin: false,
      },
      {
        name: "Clayton",
        email: "flora.terry@lumu.edu",
        password: "mR1C",
        isAdmin: false,
      },
      {
        name: "Josephine",
        email: "bobby@denomuz.org",
        password: "yW9DdbRZFp",
        isAdmin: false,
      },
      {
        name: "Alma",
        email: "julian.martinez@vigafi.org",
        password: "xxorq2v5",
        isAdmin: false,
      },
      {
        name: "Isaac",
        email: "corey.roy@mutim.co.uk",
        password: "r36NTBA",
        isAdmin: false,
      },
      {
        name: "Bryan",
        email: "albert@fazo.edu",
        password: "369hfJ",
        isAdmin: false,
      },
      {
        name: "Lawrence",
        email: "glen.poole@ifi.net",
        password: "1i6w",
        isAdmin: false,
      },
      {
        name: "Gertrude",
        email: "may@pagaf.io",
        password: "jdic0fTlh8",
        isAdmin: false,
      },
      {
        name: "Randall",
        email: "franklin@asogen.gov",
        password: "eErVwTx",
        isAdmin: false,
      },
      {
        name: "Benjamin",
        email: "dorothy.tran@uvafute.org",
        password: "0Gpoy",
        isAdmin: false,
      },
      {
        name: "Lulu",
        email: "john.clayton@himo.io",
        password: "1km1BdsJQh",
        isAdmin: false,
      },
      {
        name: "Ellen",
        email: "mason.rowe@pabi.edu",
        password: "2q6vsCNjBL",
        isAdmin: false,
      },
      {
        name: "Beatrice",
        email: "nancy.romero@neja.co.uk",
        password: "OIeuOCKQpl",
        isAdmin: false,
      },
      {
        name: "Kathryn",
        email: "elmer@rigu.edu",
        password: "TbTibI7e9Q",
        isAdmin: false,
      },
      {
        name: "Claudia",
        email: "carolyn@poroj.net",
        password: "m3r7HzF",
        isAdmin: false,
      },
      {
        name: "Mason",
        email: "edgar.wright@jokoco.org",
        password: "QkvErAXwYV",
        isAdmin: false,
      },
      {
        name: "Georgia",
        email: "clifford.carson@duwuf.io",
        password: "bbaL6",
        isAdmin: false,
      },
      {
        name: "Bruce",
        email: "marie@fit.net",
        password: "m1YDLkD1",
        isAdmin: false,
      },
      {
        name: "Susie",
        email: "shane@adod.io",
        password: "OLQAwoc1",
        isAdmin: false,
      },
      {
        name: "Oscar",
        email: "henry@bavove.io",
        password: "rzKwvBR",
        isAdmin: false,
      },
      {
        name: "Glenn",
        email: "landon@fukid.edu",
        password: "sS5cvmCWb",
        isAdmin: false,
      },
      {
        name: "Emily",
        email: "clarence.copeland@osikobe.io",
        password: "C9O24UMUQO",
        isAdmin: false,
      },
      {
        name: "Effie",
        email: "edward.estrada@wezahu.org",
        password: "BczgcTw",
        isAdmin: false,
      },
      {
        name: "Mary",
        email: "ann.rodriquez@law.org",
        password: "UAaK27",
        isAdmin: false,
      },
      {
        name: "Craig",
        email: "philip@fotubi.com",
        password: "K5rKn",
        isAdmin: false,
      },
      {
        name: "Maude",
        email: "lulu@hogo.org",
        password: "7Jqy677",
        isAdmin: false,
      },
      {
        name: "Chris",
        email: "ella.ramos@umu.gov",
        password: "uZ9Vvc",
        isAdmin: false,
      },
      {
        name: "Troy",
        email: "lenora.maldonado@koj.io",
        password: "bCpczYa97",
        isAdmin: false,
      },
      {
        name: "Angel",
        email: "chase.washington@nohah.org",
        password: "3203jaS0",
        isAdmin: false,
      },
      {
        name: "Luis",
        email: "elnora@ibuju.org",
        password: "DtEVki2Tdm",
        isAdmin: false,
      },
      {
        name: "Ida",
        email: "alfred@dawalu.org",
        password: "Boxsy4Uh0Z",
        isAdmin: false,
      },
      {
        name: "Richard",
        email: "sean@okonave.net",
        password: "49CmAJN5",
        isAdmin: false,
      },
      {
        name: "Adam",
        email: "nell.gomez@sil.net",
        password: "EBfGgtP",
        isAdmin: false,
      },
      {
        name: "Clifford",
        email: "ola@ijopo.co.uk",
        password: "C6Kik",
        isAdmin: false,
      },
      {
        name: "Nannie",
        email: "leonard@zihodi.io",
        password: "MtXRMuceT",
        isAdmin: false,
      },
      {
        name: "Joe",
        email: "dorothy.murphy@nubuw.com",
        password: "FNCmOX",
        isAdmin: false,
      },
      {
        name: "Wesley",
        email: "jeremy.warren@obari.gov",
        password: "jWMlckU",
        isAdmin: false,
      },
      {
        name: "Mamie",
        email: "stephen@cubihu.io",
        password: "pYUZ6up",
        isAdmin: false,
      },
      {
        name: "Alvin",
        email: "thomas@dufisi.com",
        password: "IAA0f7iFZ",
        isAdmin: false,
      },
      {
        name: "Rosalie",
        email: "dustin@pake.com",
        password: "SZA2j",
        isAdmin: false,
      },
      {
        name: "Agnes",
        email: "william@otorur.net",
        password: "8GguMgk",
        isAdmin: false,
      },
      {
        name: "Edna",
        email: "maurice.grant@opor.gov",
        password: "5tW7Aq",
        isAdmin: false,
      },
      {
        name: "Edwin",
        email: "bertha.cohen@igab.co.uk",
        password: "v8nLJVk",
        isAdmin: false,
      },
      {
        name: "Hilda",
        email: "amanda@pogog.net",
        password: "Rd6nMyecgy",
        isAdmin: false,
      },
      {
        name: "Eric",
        email: "lottie.delgado@ligog.gov",
        password: "vMNqUgBGL",
        isAdmin: false,
      },
      {
        name: "Adrian",
        email: "glen@vipi.edu",
        password: "uJWIQWL",
        isAdmin: false,
      },
      {
        name: "Herbert",
        email: "amy.blair@ruwokad.net",
        password: "awAoKyV6p",
        isAdmin: false,
      },
      {
        name: "Lee",
        email: "seth@mesa.io",
        password: "qFZlqTx",
        isAdmin: false,
      },
      {
        name: "Allie",
        email: "aiden.palmer@samoso.gov",
        password: "jg5pX",
        isAdmin: false,
      },
      {
        name: "Patrick",
        email: "steven.knight@tehi.edu",
        password: "aaH5bfh9",
        isAdmin: false,
      },
      {
        name: "Eric",
        email: "sam@guvo.co.uk",
        password: "1lmJ",
        isAdmin: false,
      },
      {
        name: "Brent",
        email: "bernard.quinn@emukaf.io",
        password: "8RFT7Xd",
        isAdmin: false,
      },
      {
        name: "Nora",
        email: "willie.welch@cehov.net",
        password: "ANeRujMusr",
        isAdmin: false,
      },
      {
        name: "Ronnie",
        email: "francis@nazar.co.uk",
        password: "PAxV",
        isAdmin: false,
      },
      {
        name: "Annie",
        email: "agnes.copeland@kini.io",
        password: "MTu9d",
        isAdmin: false,
      },
      {
        name: "Barry",
        email: "elijah@noworep.net",
        password: "Up7awP9",
        isAdmin: false,
      },
      {
        name: "Ralph",
        email: "hattie.barton@redino.gov",
        password: "P6OnePNfwq",
        isAdmin: false,
      },
      {
        name: "Andre",
        email: "victor.medina@wale.gov",
        password: "lzKBf",
        isAdmin: false,
      },
      {
        name: "Sara",
        email: "bettie@pip.io",
        password: "w94HYtsjq",
        isAdmin: false,
      },
      {
        name: "Fannie",
        email: "lucy@cuwa.com",
        password: "YA0Jerc58",
        isAdmin: false,
      },
      {
        name: "Shawn",
        email: "franklin@mar.io",
        password: "P2TLiq",
        isAdmin: false,
      },
      {
        name: "Wayne",
        email: "duane.powell@cuwi.edu",
        password: "Ru3M2",
        isAdmin: false,
      },
      {
        name: "Benjamin",
        email: "madge.ortega@aco.org",
        password: "n3LIFk73Y",
        isAdmin: false,
      },
      {
        name: "Barbara",
        email: "nettie.ward@epuhu.edu",
        password: "ZpTuxA",
        isAdmin: false,
      },
      {
        name: "Catherine",
        email: "douglas.schultz@logema.com",
        password: "5uwsuXAI",
        isAdmin: false,
      },
      {
        name: "Dorothy",
        email: "ruth@atun.net",
        password: "65Y0zeU9J",
        isAdmin: false,
      },
      {
        name: "Della",
        email: "belle@pezafa.edu",
        password: "MY6Oq",
        isAdmin: false,
      },
      {
        name: "Vincent",
        email: "curtis@zutukil.edu",
        password: "7Bi5x",
        isAdmin: false,
      },
      {
        name: "Lenora",
        email: "john.webb@voconi.io",
        password: "jXC4dZhqr",
        isAdmin: false,
      },
      {
        name: "Mollie",
        email: "alex@lusapa.edu",
        password: "omAIhi",
        isAdmin: false,
      },
      {
        name: "Lucinda",
        email: "sophie@cez.edu",
        password: "6RvBDai",
        isAdmin: false,
      },
      {
        name: "Clarence",
        email: "george.rodriguez@fiwi.edu",
        password: "zXGVWe6CS",
        isAdmin: false,
      },
      {
        name: "Bertie",
        email: "raymond@nadubiz.io",
        password: "ZvanT6nyb",
        isAdmin: false,
      },
      {
        name: "Ronnie",
        email: "marc.murphy@papu.edu",
        password: "Qq1XAx",
        isAdmin: false,
      },
      {
        name: "Brett",
        email: "allen.riley@vul.org",
        password: "wemhdj",
        isAdmin: false,
      },
      {
        name: "Delia",
        email: "gabriel.brock@gomi.edu",
        password: "yV9BFhmNt",
        isAdmin: false,
      },
      {
        name: "Adelaide",
        email: "henrietta@rar.net",
        password: "MFOm",
        isAdmin: false,
      },
      {
        name: "Dorothy",
        email: "ralph@dafubo.co.uk",
        password: "RrMXe",
        isAdmin: false,
      },
      {
        name: "Agnes",
        email: "jeff.black@kejugu.com",
        password: "i0qLqT",
        isAdmin: false,
      },
      {
        name: "Rose",
        email: "olive@vipuvu.edu",
        password: "aYBdwZIZ1",
        isAdmin: false,
      },
      {
        name: "Alta",
        email: "ronnie.townsend@tuwubif.com",
        password: "loXu",
        isAdmin: false,
      },
      {
        name: "Cora",
        email: "mittie@zit.net",
        password: "cWkmyD",
        isAdmin: false,
      },
      {
        name: "Alberta",
        email: "mamie@avaz.co.uk",
        password: "ErHItt",
        isAdmin: false,
      },
      {
        name: "Lottie",
        email: "sadie.haynes@fuben.co.uk",
        password: "kjoDg",
        isAdmin: false,
      },
      {
        name: "Betty",
        email: "ernest.rios@decewek.co.uk",
        password: "nAsW",
        isAdmin: false,
      },
      {
        name: "Charlie",
        email: "warren@goni.net",
        password: "JuPN9Bvrt",
        isAdmin: false,
      },
      {
        name: "Justin",
        email: "clayton.steele@cuza.org",
        password: "j765q",
        isAdmin: false,
      },
      {
        name: "Alan",
        email: "susan.cooper@vep.edu",
        password: "majsk6vC2",
        isAdmin: false,
      },
      {
        name: "Carlos",
        email: "jeremiah.bryant@nehevur.org",
        password: "K57ett",
        isAdmin: false,
      },
      {
        name: "Clifford",
        email: "dennis.mann@veluw.com",
        password: "GqdfaLL",
        isAdmin: false,
      },
      {
        name: "Joseph",
        email: "allie.wise@bowurow.io",
        password: "WpUlUt5IkB",
        isAdmin: false,
      },
      {
        name: "Gilbert",
        email: "matilda@ipu.com",
        password: "hAwE",
        isAdmin: false,
      },
      {
        name: "Charlotte",
        email: "ray@safaz.net",
        password: "LSM1ly0w",
        isAdmin: false,
      },
      {
        name: "Sylvia",
        email: "leila@ewateti.co.uk",
        password: "WuXbQSn",
        isAdmin: false,
      },
      {
        name: "Rodney",
        email: "mittie@topahe.com",
        password: "C2wvsXl",
        isAdmin: false,
      },
      {
        name: "Logan",
        email: "roxie.schwartz@zagufav.org",
        password: "z9ZE58GK4b",
        isAdmin: false,
      },
      {
        name: "Curtis",
        email: "mae@suzofo.net",
        password: "yDW1hihR6",
        isAdmin: false,
      },
      {
        name: "Edwin",
        email: "violet@kuwa.org",
        password: "XqGRb",
        isAdmin: false,
      },
      {
        name: "Cordelia",
        email: "nell@ini.edu",
        password: "YpsWib2ZCW",
        isAdmin: false,
      },
      {
        name: "Roy",
        email: "ryan@zanema.org",
        password: "BBZMAu6f",
        isAdmin: false,
      },
      {
        name: "Ernest",
        email: "lelia.figueroa@jazokur.edu",
        password: "2te0V",
        isAdmin: false,
      },
      {
        name: "Dominic",
        email: "peter@pitud.gov",
        password: "7uF77n",
        isAdmin: false,
      },
      {
        name: "Gilbert",
        email: "oscar.rice@niwizas.net",
        password: "G8TW",
        isAdmin: false,
      },
      {
        name: "Norman",
        email: "sam.cole@dov.com",
        password: "X24Ba75yzB",
        isAdmin: false,
      },
      {
        name: "Viola",
        email: "clarence.cain@cofebup.io",
        password: "AlJzqNk",
        isAdmin: false,
      },
      {
        name: "Sam",
        email: "ian@gerok.co.uk",
        password: "wCmLO9",
        isAdmin: false,
      },
      {
        name: "Jason",
        email: "alta.norris@mudezog.edu",
        password: "fuGJ",
        isAdmin: false,
      },
      {
        name: "Jerry",
        email: "ann.richards@fudukud.net",
        password: "sLDfVGMU8",
        isAdmin: false,
      },
      {
        name: "Aaron",
        email: "albert@lujuji.gov",
        password: "qQxBt",
        isAdmin: false,
      },
      {
        name: "Rosalie",
        email: "phillip.rowe@zamet.org",
        password: "Nj6V",
        isAdmin: false,
      },
      {
        name: "Ellen",
        email: "etta.mack@wab.org",
        password: "nYx94ln",
        isAdmin: false,
      },
      {
        name: "Yudho",
        email: "yudho@yudho.com",
        password: "admin123",
        isAdmin: true,
      },
      {
        name: "Cordelia",
        email: "cornelia.buchanan@vafib.net",
        password: "25ERn",
        isAdmin: false,
      },
      {
        name: "Anthony",
        email: "marion@baca.org",
        password: "otHp1B",
        isAdmin: false,
      },
      {
        name: "Isabel",
        email: "elva.marsh@nuh.io",
        password: "gwmH",
        isAdmin: false,
      },
      {
        name: "Alvin",
        email: "roger.estrada@unofo.io",
        password: "Xqb7rs",
        isAdmin: false,
      },
      {
        name: "Henrietta",
        email: "ollie@omew.net",
        password: "sv6OsQeag",
        isAdmin: false,
      },
      {
        name: "Georgie",
        email: "sallie@pelide.edu",
        password: "AsgBbbyW",
        isAdmin: false,
      },
      {
        name: "Callie",
        email: "martin@lesuhib.edu",
        password: "jsq7oWqv",
        isAdmin: false,
      },
      {
        name: "Cordelia",
        email: "brett@zek.io",
        password: "W4A566",
        isAdmin: false,
      },
      {
        name: "Victoria",
        email: "willie.haynes@rat.edu",
        password: "y0fKoIgn",
        isAdmin: false,
      },
      {
        name: "Millie",
        email: "isabel@etinig.edu",
        password: "Q8emTMZ",
        isAdmin: false,
      },
      {
        name: "Lela",
        email: "may@ner.com",
        password: "5FeAwm2jq",
        isAdmin: false,
      },
      {
        name: "Alvin",
        email: "helen.simon@bunuwe.com",
        password: "XuPCc7W14B",
        isAdmin: false,
      },
      {
        name: "Grace",
        email: "olivia@howom.io",
        password: "2encWQru",
        isAdmin: false,
      },
      {
        name: "Marguerite",
        email: "lillie.zimmerman@iho.gov",
        password: "wTxSRV",
        isAdmin: false,
      },
      {
        name: "Jessie",
        email: "elva@keke.com",
        password: "yQYvN",
        isAdmin: false,
      },
      {
        name: "Rachel",
        email: "ryan.hill@ruj.io",
        password: "dwjW",
        isAdmin: false,
      },
      {
        name: "Herman",
        email: "isaiah@ragemu.gov",
        password: "mL1r5s4A9",
        isAdmin: false,
      },
      {
        name: "George",
        email: "charlie.craig@ebuzi.gov",
        password: "H0qymk9Yb",
        isAdmin: false,
      },
      {
        name: "Hannah",
        email: "joshua.adkins@rig.co.uk",
        password: "Kz8pZm0Jrl",
        isAdmin: false,
      },
      {
        name: "Leon",
        email: "callie.barnett@vuti.com",
        password: "EdsPW",
        isAdmin: false,
      },
      {
        name: "Francis",
        email: "chase@vuhagub.com",
        password: "jPq0",
        isAdmin: false,
      },
      {
        name: "Donald",
        email: "oscar.ellis@zurona.org",
        password: "rgLC",
        isAdmin: false,
      },
      {
        name: "Eddie",
        email: "theresa@tedatuj.com",
        password: "PbI4NDh",
        isAdmin: false,
      },
      {
        name: "Ann",
        email: "esther@wuf.net",
        password: "fVPkjm",
        isAdmin: false,
      },
      {
        name: "Nathan",
        email: "matilda.clayton@jodos.net",
        password: "ry5n7XzAe",
        isAdmin: false,
      },
      {
        name: "Effie",
        email: "sylvia.walker@udus.edu",
        password: "UgFKp5NJ",
        isAdmin: false,
      },
      {
        name: "Nathan",
        email: "estella@tavu.co.uk",
        password: "qKSwjH",
        isAdmin: false,
      },
      {
        name: "Lily",
        email: "laura@iripuno.org",
        password: "zwsoA05z4",
        isAdmin: false,
      },
      {
        name: "Ricardo",
        email: "jeffery@cure.gov",
        password: "NxbcYIS",
        isAdmin: false,
      },
      {
        name: "Anne",
        email: "steve.barnes@odabaf.io",
        password: "hBFNrH",
        isAdmin: false,
      },
      {
        name: "Bertha",
        email: "benjamin.reynolds@cufaga.net",
        password: "NOpEYfpv",
        isAdmin: false,
      },
      {
        name: "Myrtle",
        email: "julian@ofi.gov",
        password: "3mbHbv4F",
        isAdmin: false,
      },
      {
        name: "Carolyn",
        email: "isabel.hudson@ajavo.net",
        password: "w0GhZFSH",
        isAdmin: false,
      },
      {
        name: "Christopher",
        email: "fred@sab.edu",
        password: "z9yLgx",
        isAdmin: false,
      },
      {
        name: "Susan",
        email: "angel@iwej.com",
        password: "oUWKD",
        isAdmin: false,
      },
      {
        name: "Ralph",
        email: "rebecca.holt@leb.com",
        password: "EHf0yDpGMM",
        isAdmin: false,
      },
      {
        name: "Elva",
        email: "harvey@isug.co.uk",
        password: "HZ8BVUDk",
        isAdmin: false,
      },
      {
        name: "Cameron",
        email: "jorge.briggs@zebo.net",
        password: "dAXH",
        isAdmin: false,
      },
      {
        name: "Virginia",
        email: "vernon.maldonado@kokujog.io",
        password: "uAj69TIQe4",
        isAdmin: false,
      },
      {
        name: "Florence",
        email: "nell.dean@golam.io",
        password: "mh8A9cW",
        isAdmin: false,
      },
      {
        name: "Caroline",
        email: "nettie.horton@zojovit.com",
        password: "RTD8eplV3c",
        isAdmin: false,
      },
      {
        name: "Viola",
        email: "maurice@wef.net",
        password: "cJBwwuUx",
        isAdmin: false,
      },
      {
        name: "Evan",
        email: "mollie@niciho.io",
        password: "gFXg",
        isAdmin: false,
      },
      {
        name: "Jerry",
        email: "john@budeher.co.uk",
        password: "QAMScw",
        isAdmin: false,
      },
      {
        name: "Julian",
        email: "william@ofoc.edu",
        password: "sAH0TuXO",
        isAdmin: false,
      },
      {
        name: "May",
        email: "mitchell.miles@pumizof.edu",
        password: "dPc8MUp",
        isAdmin: false,
      },
      {
        name: "Lura",
        email: "lucy.walters@vin.net",
        password: "Gl8IX",
        isAdmin: false,
      },
      {
        name: "Kathryn",
        email: "fannie@lisasa.co.uk",
        password: "TSwfo",
        isAdmin: false,
      },
      {
        name: "Lida",
        email: "myrtle@cebef.net",
        password: "FEKMC",
        isAdmin: false,
      },
      {
        name: "Sylvia",
        email: "jerry.ryan@zerot.org",
        password: "CKNr1GD",
        isAdmin: false,
      },
      {
        name: "Lewis",
        email: "ann@berug.gov",
        password: "qfo3Gbk",
        isAdmin: false,
      },
      {
        name: "Ella",
        email: "virginia@bated.net",
        password: "kgYb",
        isAdmin: false,
      },
      {
        name: "Amy",
        email: "loretta.douglas@netirer.edu",
        password: "STGKyl",
        isAdmin: false,
      },
      {
        name: "Jack",
        email: "charlotte.curry@unu.net",
        password: "o1A50Q6vNN",
        isAdmin: false,
      },
      {
        name: "Glen",
        email: "lena.terry@zeb.io",
        password: "TUEt7XGC",
        isAdmin: false,
      },
      {
        name: "Helen",
        email: "garrett@tugup.net",
        password: "IxzjNo2ohs",
        isAdmin: false,
      },
      {
        name: "Ellen",
        email: "herbert.ward@megot.edu",
        password: "kfFf3jg",
        isAdmin: false,
      },
      {
        name: "Adrian",
        email: "florence.mcdonald@bulohej.gov",
        password: "KMZ5m8m",
        isAdmin: false,
      },
      {
        name: "Jorge",
        email: "glenn@reh.com",
        password: "xyzjzb",
        isAdmin: false,
      },
      {
        name: "Bill",
        email: "belle.morton@oron.edu",
        password: "tDVI",
        isAdmin: false,
      },
      {
        name: "Lois",
        email: "sophia.rose@zozaci.co.uk",
        password: "WKZc9",
        isAdmin: false,
      },
      {
        name: "Hallie",
        email: "lucile@vehezih.io",
        password: "dO44",
        isAdmin: false,
      },
      {
        name: "Maurice",
        email: "steven.mcdaniel@daw.org",
        password: "1tMVGSA8",
        isAdmin: false,
      },
      {
        name: "Gene",
        email: "john.clark@jisowef.edu",
        password: "Ofa9fKSJS",
        isAdmin: false,
      },
      {
        name: "Lydia",
        email: "georgia@umew.org",
        password: "lylrqi",
        isAdmin: false,
      },
      {
        name: "Matilda",
        email: "andre.floyd@waw.io",
        password: "VavzR",
        isAdmin: false,
      },
      {
        name: "Oscar",
        email: "clayton@tiwe.co.uk",
        password: "Wg9EJ4k",
        isAdmin: false,
      },
      {
        name: "Sarah",
        email: "jose@guf.edu",
        password: "ya1OV",
        isAdmin: false,
      },
      {
        name: "Lucile",
        email: "leroy.beck@dohedi.edu",
        password: "RYoD",
        isAdmin: false,
      },
      {
        name: "Tyler",
        email: "mina@cizihe.org",
        password: "ezZg",
        isAdmin: false,
      },
      {
        name: "Jesus",
        email: "mason.bell@nibar.net",
        password: "oOAE",
        isAdmin: false,
      },
      {
        name: "Samuel",
        email: "polly.holland@omotavo.co.uk",
        password: "iJBpLr",
        isAdmin: false,
      },
      {
        name: "Iva",
        email: "vera@wuj.co.uk",
        password: "uEttk",
        isAdmin: false,
      },
      {
        name: "Phoebe",
        email: "verna@tafoguk.org",
        password: "6tSJU",
        isAdmin: false,
      },
      {
        name: "Donald",
        email: "theodore@vuhevi.co.uk",
        password: "Jrp3",
        isAdmin: false,
      },
      {
        name: "Carlos",
        email: "christopher@tutug.io",
        password: "a3hFarvw5",
        isAdmin: false,
      },
      {
        name: "Andrew",
        email: "lucas.glover@nula.io",
        password: "A9z6YB",
        isAdmin: false,
      },
      {
        name: "Adelaide",
        email: "myrtie.harris@gateja.io",
        password: "iVwz",
        isAdmin: false,
      },
      {
        name: "Vera",
        email: "mae.johnson@zotuf.net",
        password: "0BPSA",
        isAdmin: false,
      },
      {
        name: "Katherine",
        email: "donald@woc.com",
        password: "8V5uRD",
        isAdmin: false,
      },
      {
        name: "Christopher",
        email: "glen@ivurib.net",
        password: "IRzTdOXiV",
        isAdmin: false,
      },
      {
        name: "Jayden",
        email: "eric@kawu.io",
        password: "T7RHwDu",
        isAdmin: false,
      },
      {
        name: "Joel",
        email: "edgar.dennis@curo.edu",
        password: "Ckk1k0Rlhj",
        isAdmin: false,
      },
      {
        name: "Harriett",
        email: "randall@keje.com",
        password: "ul8a",
        isAdmin: false,
      },
      {
        name: "Carlos",
        email: "olga.cross@pit.edu",
        password: "1XNgjTxFi",
        isAdmin: false,
      },
      {
        name: "Ophelia",
        email: "kenneth@daridos.co.uk",
        password: "1Xeh",
        isAdmin: false,
      },
      {
        name: "Rena",
        email: "albert@jiwu.org",
        password: "51GWjf",
        isAdmin: false,
      },
      {
        name: "Jacob",
        email: "arthur.harrison@taturuk.edu",
        password: "mPNV4hu",
        isAdmin: false,
      },
      {
        name: "Corey",
        email: "ivan.fisher@ibuv.org",
        password: "rjABHBBCjV",
        isAdmin: false,
      },
      {
        name: "Alejandro",
        email: "alex@jetim.gov",
        password: "KafRSI8i21",
        isAdmin: false,
      },
      {
        name: "Gordon",
        email: "garrett@cuh.io",
        password: "LqXB3WEZ",
        isAdmin: false,
      },
      {
        name: "Terry",
        email: "rachel@ikufa.net",
        password: "tw2ApfBpit",
        isAdmin: false,
      },
      {
        name: "Maurice",
        email: "kyle@emoro.io",
        password: "dbRrRDK",
        isAdmin: false,
      },
      {
        name: "Connor",
        email: "duane.anderson@azad.io",
        password: "DmlzWrjN",
        isAdmin: false,
      },
      {
        name: "Clara",
        email: "mason@geta.co.uk",
        password: "AwyM6xGlVN",
        isAdmin: false,
      },
      {
        name: "Lois",
        email: "clarence.lee@evo.io",
        password: "GwkUy",
        isAdmin: false,
      },
      {
        name: "Loretta",
        email: "jared@zuzehen.net",
        password: "KztNQH",
        isAdmin: false,
      },
      {
        name: "Austin",
        email: "roy@tasul.co.uk",
        password: "NUzD6j",
        isAdmin: false,
      },
      {
        name: "Joel",
        email: "floyd.moss@dibamim.io",
        password: "QfvWoYWL72",
        isAdmin: false,
      },
      {
        name: "Cordelia",
        email: "lou.brewer@pagumob.net",
        password: "sddCu",
        isAdmin: false,
      },
      {
        name: "Rebecca",
        email: "maurice@vutu.io",
        password: "Z7WmwFxrQ",
        isAdmin: false,
      },
      {
        name: "Max",
        email: "jeffrey.phillips@nuzemu.com",
        password: "ZOQG",
        isAdmin: false,
      },
      {
        name: "Jane",
        email: "vernon.hines@hira.gov",
        password: "Hm8X49t5L",
        isAdmin: false,
      },
      {
        name: "Stephen",
        email: "gabriel@cocew.gov",
        password: "hZ11rSKgD",
        isAdmin: false,
      },
      {
        name: "Jennie",
        email: "gussie@wok.org",
        password: "yXg5l",
        isAdmin: false,
      },
      {
        name: "Rodney",
        email: "john.farmer@gekot.gov",
        password: "F9qxW",
        isAdmin: false,
      },
      {
        name: "Mabel",
        email: "chris.bennett@ipit.com",
        password: "SEgbGMaM",
        isAdmin: false,
      },
      {
        name: "Lester",
        email: "jane@jakudaf.io",
        password: "1P19Dn5RM",
        isAdmin: false,
      },
      {
        name: "Eric",
        email: "chester@higadu.gov",
        password: "wMwJrMtl6",
        isAdmin: false,
      },
      {
        name: "Luis",
        email: "rebecca.gonzalez@lujekal.com",
        password: "2Er7wx1",
        isAdmin: false,
      },
      {
        name: "Claudia",
        email: "noah.garner@kal.io",
        password: "7BJgGFl42U",
        isAdmin: false,
      },
      {
        name: "Gary",
        email: "jennie.rhodes@kosu.edu",
        password: "roxIZCPu2",
        isAdmin: false,
      },
      {
        name: "Miguel",
        email: "roy@gefel.com",
        password: "blL40BP",
        isAdmin: false,
      },
      {
        name: "Beatrice",
        email: "rose@bewime.org",
        password: "GrZ3I",
        isAdmin: false,
      },
      {
        name: "Cynthia",
        email: "jeff.pierce@belovog.net",
        password: "vKdar2bdeC",
        isAdmin: false,
      },
      {
        name: "Nathaniel",
        email: "dennis.hudson@abi.gov",
        password: "UfCCM",
        isAdmin: false,
      },
      {
        name: "Austin",
        email: "della@tubuwic.gov",
        password: "D8wpF",
        isAdmin: false,
      },
      {
        name: "Bryan",
        email: "jesse@hosiju.io",
        password: "SWuMA",
        isAdmin: false,
      },
      {
        name: "Aaron",
        email: "nellie@negih.co.uk",
        password: "eqxqXs",
        isAdmin: false,
      },
      {
        name: "Janie",
        email: "lillian.day@bisem.org",
        password: "mLnBc",
        isAdmin: false,
      },
      {
        name: "Jayden",
        email: "alta@itodiv.edu",
        password: "1PJ5WgX",
        isAdmin: false,
      },
      {
        name: "Norman",
        email: "joe@sepor.com",
        password: "thQtS",
        isAdmin: false,
      },
      {
        name: "Helena",
        email: "margaret.mccarthy@nacebiw.io",
        password: "W8LGR2V2",
        isAdmin: false,
      },
      {
        name: "Hettie",
        email: "phoebe@jezodah.io",
        password: "Nl9nz",
        isAdmin: false,
      },
      {
        name: "Harriett",
        email: "miguel@noci.co.uk",
        password: "F5WZ3",
        isAdmin: false,
      },
      {
        name: "Gavin",
        email: "alice.butler@ralo.edu",
        password: "sdwrrH",
        isAdmin: false,
      },
      {
        name: "Louis",
        email: "leonard.pena@few.gov",
        password: "1wzmq",
        isAdmin: false,
      },
      {
        name: "Lucy",
        email: "alan.hines@jitipoh.com",
        password: "mL5g",
        isAdmin: false,
      },
      {
        name: "Evelyn",
        email: "leonard@fefuwa.edu",
        password: "L2aHZJcgw1",
        isAdmin: false,
      },
      {
        name: "Emilie",
        email: "alexander@ukeg.gov",
        password: "HTB7",
        isAdmin: false,
      },
      {
        name: "Caroline",
        email: "henry@sise.co.uk",
        password: "WiAofHw",
        isAdmin: false,
      },
      {
        name: "Brent",
        email: "theodore@hitage.org",
        password: "suuyJWwyu",
        isAdmin: false,
      },
      {
        name: "Mabelle",
        email: "ellen@podol.com",
        password: "4EuvS",
        isAdmin: false,
      },
      {
        name: "Trevor",
        email: "paul@tos.io",
        password: "Dd47WaL5p",
        isAdmin: false,
      },
      {
        name: "Virgie",
        email: "duane@ujowi.gov",
        password: "FidyzJ",
        isAdmin: false,
      },
      {
        name: "Inez",
        email: "harvey.jimenez@icij.org",
        password: "gJYFsP",
        isAdmin: false,
      },
      {
        name: "Nathan",
        email: "nannie@saba.org",
        password: "LH5Lxb0A1",
        isAdmin: false,
      },
      {
        name: "George",
        email: "lenora@mug.org",
        password: "k08sTd",
        isAdmin: false,
      },
      {
        name: "Susie",
        email: "rena.martinez@hugun.org",
        password: "HtENM",
        isAdmin: false,
      },
      {
        name: "Arthur",
        email: "phillip@mipevuf.io",
        password: "gRkmHTCs",
        isAdmin: false,
      },
      {
        name: "Bettie",
        email: "ernest@bar.io",
        password: "4rI7",
        isAdmin: false,
      },
      {
        name: "Jackson",
        email: "manuel.lyons@gin.gov",
        password: "mBYa",
        isAdmin: false,
      },
      {
        name: "Blanche",
        email: "roxie.fowler@nojesa.gov",
        password: "xSFxu",
        isAdmin: false,
      },
      {
        name: "Scott",
        email: "kenneth.howard@mevuhu.org",
        password: "DIuxSdRZ",
        isAdmin: false,
      },
      {
        name: "Ronald",
        email: "alejandro.osborne@deki.io",
        password: "GxQgGxaf",
        isAdmin: false,
      },
      {
        name: "Inez",
        email: "harriet.campbell@oma.com",
        password: "qJjt",
        isAdmin: false,
      },
      {
        name: "Nellie",
        email: "miguel.craig@hajurar.gov",
        password: "lAQX0sk",
        isAdmin: false,
      },
      {
        name: "Martha",
        email: "mary.cunningham@hopa.gov",
        password: "DzBAXViN",
        isAdmin: false,
      },
      {
        name: "Eunice",
        email: "jeanette.medina@lihob.edu",
        password: "46WI8fZzG",
        isAdmin: false,
      },
      {
        name: "Danny",
        email: "birdie.cross@rabowa.edu",
        password: "BJh02gaT",
        isAdmin: false,
      },
      {
        name: "Kenneth",
        email: "dollie@uzul.com",
        password: "uwRxuf42o",
        isAdmin: false,
      },
      {
        name: "Dennis",
        email: "jose@beciveh.gov",
        password: "6BXOmVlu",
        isAdmin: false,
      },
      {
        name: "Eunice",
        email: "sue@zikaf.org",
        password: "pvfs9MRQ",
        isAdmin: false,
      },
      {
        name: "Vera",
        email: "josie@wepa.edu",
        password: "CyagUanRX",
        isAdmin: false,
      },
      {
        name: "Lucille",
        email: "myrtie@ohes.com",
        password: "9CQCY",
        isAdmin: false,
      },
      {
        name: "Franklin",
        email: "stephen@vibu.com",
        password: "Dl2XOB",
        isAdmin: false,
      },
      {
        name: "William",
        email: "randall@rire.gov",
        password: "hlJ03F9",
        isAdmin: false,
      },
      {
        name: "Louisa",
        email: "jack@fofopom.org",
        password: "YXSf",
        isAdmin: false,
      },
      {
        name: "Nina",
        email: "kathryn@keza.io",
        password: "y7evQV",
        isAdmin: false,
      },
      {
        name: "Joshua",
        email: "francis@udagoz.com",
        password: "MmKS0",
        isAdmin: false,
      },
      {
        name: "Stanley",
        email: "leo@ipav.io",
        password: "DkGVJxMB",
        isAdmin: false,
      },
      {
        name: "Viola",
        email: "esther@fotuca.net",
        password: "SILgc",
        isAdmin: false,
      },
      {
        name: "Nelle",
        email: "estelle.ramirez@useholo.io",
        password: "AyZH",
        isAdmin: false,
      },
      {
        name: "Jim",
        email: "lenora.cox@ane.gov",
        password: "Xw0IhFp",
        isAdmin: false,
      },
      {
        name: "Dollie",
        email: "margaret.santos@wibofe.edu",
        password: "PvGsdW",
        isAdmin: false,
      },
      {
        name: "Polly",
        email: "marie.reid@jukavuc.edu",
        password: "YAt4",
        isAdmin: false,
      },
      {
        name: "Joe",
        email: "steven@cisecic.io",
        password: "O54ACMKhhk",
        isAdmin: false,
      },
      {
        name: "Sally",
        email: "sarah.lowe@bebufe.org",
        password: "4SK0",
        isAdmin: false,
      },
      {
        name: "Harry",
        email: "carrie@owubiza.co.uk",
        password: "apTDS",
        isAdmin: false,
      },
    ],
  };
  
const databaseDataArray = database.data;
let databaseDataAdmin = [];
let databaseDataNonAdmin = [];
let databaseDataPassword = [];

//    1. Print sebuah array yang berisi string email pengguna yang menjadi admin.
console.log('===JAWABAN NO.1===')
for (let i = 0; i < databaseDataArray.length; i++){
    if (databaseDataArray[i]['isAdmin'] === true){
        databaseDataAdmin.push(databaseDataArray[i]['email'])
        }
    if (databaseDataArray[i]['isAdmin'] === false){
        databaseDataNonAdmin.push(databaseDataArray[i]['email'])
        }
    };
console.log(databaseDataAdmin);

//    2. Print sebuah array yang berisi object pengguna yang panjang passwordnya kurang dari 8.
console.log('===JAWABAN NO.2===')
for (let a = 0; a < databaseDataArray.length; a++){
    if (databaseDataArray[a]['password'].length < 8){
        databaseDataPassword.push(databaseDataArray[a])
    }
}
console.log(databaseDataPassword);

//    3. Print sebuah array yang berisi string name pengguna yang emailnya di-blacklist.
console.log('===JAWABAN NO.3===')
const blacklistedEmail = databaseDataArray.filter(function (element){
    return BLACKLISTED_EMAILS.includes(element.email);
});
console.log(blacklistedEmail);

//    4. Print sebuah Object dengan struktur seperti berikut.
//       {
//           totalData: …,
//           totalAdmin: …,
//           totalNonAdmin: …,
//       }
//       Lengkapi object tersebut dengan mencari totalData, totalAdmin, dan totalNonAdmin.
console.log('===JAWABAN NO.4===')
let totalData = databaseDataArray.length;
let totalAdmin = databaseDataAdmin.length;
let totalNonAdmin = databaseDataNonAdmin.length;
console.log(`{totalData: ${totalData}, totalAdmin: ${totalAdmin}, totalNonAdmin: ${totalNonAdmin}}`)







